obj-$(CONFIG_MFD_SM570X) += sm570x-core-mod.o
sm570x-core-mod-y := sm570x-core.o sm570x-irq.o
obj-$(CONFIG_BATTERY_SM570X_FG) += sm570x-fuelgauge.o
obj-$(CONFIG_CHARGER_SM570X)    += sm570x-charger.o
